#!/usr/bin/env node
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { compactImportPath, compactModuleFields } from "./module_map_format.mjs";
const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = resolve(repositoryRoot, "src");
const outputPath = resolve(repositoryRoot, "docs/module-map.md");
const SOURCE_EXTENSIONS = new Set([".cjs", ".css", ".html", ".js", ".mjs"]);
const TEST_SUFFIX = ".test.mjs";
function compareText(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}
function repositoryPath(path) {
  return relative(repositoryRoot, path).split(sep).join("/");
}
async function collectSourceFiles(directory, files = []) {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      await collectSourceFiles(path, files);
    } else if (entry.isFile() && SOURCE_EXTENSIONS.has(extname(entry.name).toLowerCase())) {
      files.push(path);
    }
  }
  return files;
}
function uniqueSorted(values) {
  return [...new Set(values)].sort(compareText);
}
function publicExports(text, extension) {
  if (![".cjs", ".js", ".mjs"].includes(extension)) return [];
  const names = [];
  const declaration = /\bexport\s+(?:async\s+)?(?:class|const|function|let|var)\s+([A-Za-z_$][\w$]*)/g;
  const named = /\bexport\s*\{([^}]*)\}/g;
  const namespace = /\bexport\s*\*\s+as\s+([A-Za-z_$][\w$]*)\s+from\b/g;
  let match;
  if (/\bexport\s+default\b/.test(text)) names.push("default");
  while ((match = declaration.exec(text))) names.push(match[1]);
  while ((match = namespace.exec(text))) names.push(match[1]);
  while ((match = named.exec(text))) {
    for (const item of match[1].split(",")) {
      const parts = item.trim().split(/\s+as\s+/);
      if (parts[0]) names.push(parts.at(-1).trim());
    }
  }
  if (/\bexport\s*\*\s+from\b/.test(text)) names.push("*");
  return uniqueSorted(names);
}
function directImports(text, extension) {
  const imports = [];
  const staticImport = /\bimport\s+(?:[^"'`;]*?\s+from\s+)?["']([^"']+)["']/g;
  const dynamicImport = /\bimport\s*\(\s*["']([^"']+)["']/g;
  const reExport = /\bexport\s+(?:\*(?:\s+as\s+\w+)?|\{[^}]*\})\s+from\s+["']([^"']+)["']/g;
  const htmlDependency = /<(?:link|script)\b[^>]*?\b(?:href|src)\s*=\s*["']([^"']+)["']/gi;
  const cssImport = /@import\s+(?:url\(\s*)?["']?([^"')\s;]+)/gi;
  const patterns = [staticImport, dynamicImport, reExport];
  if (extension === ".html") patterns.push(htmlDependency);
  if (extension === ".css") patterns.push(cssImport);
  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(text))) imports.push(match[1]);
  }
  return uniqueSorted(imports).map(value => compactImportPath(
    value.startsWith(".") && value.endsWith(".mjs") ? value.slice(0, -4) : value,
  ));
}
function measure(buffer) {
  const lines = buffer.toString("utf8").split(/\r?\n/);
  if (lines.at(-1) === "") lines.pop();
  return {
    lines: lines.length,
    bytes: buffer.length,
    longestLineBytes: lines.reduce(
      (longest, line) => Math.max(longest, Buffer.byteLength(line)),
      0,
    ),
  };
}
function fieldLines(label, values) {
  if (!values.length) return [];
  const lines = [];
  let line = `  - ${label} `;
  const tokens = values.map((value, index) => (
    `${value}${index === values.length - 1 ? "" : ", "}`
  ));
  for (const token of tokens) {
    if (Buffer.byteLength(line + token) > 150) {
      lines.push(line.trimEnd());
      line = `    ${token}`;
    } else {
      line += token;
    }
  }
  lines.push(line.trimEnd());
  return lines;
}
const sourceFiles = (await collectSourceFiles(sourceRoot)).sort(compareText);
const allPaths = new Set(sourceFiles.map(repositoryPath));
const modules = sourceFiles.filter(path => !path.endsWith(TEST_SUFFIX));
const rows = await Promise.all(modules.map(async path => {
  const buffer = await readFile(path);
  const text = buffer.toString("utf8");
  const extension = extname(path).toLowerCase();
  const mappedPath = repositoryPath(path);
  const testPath = mappedPath.replace(/\.[^.]+$/, TEST_SUFFIX);
  return {
    path: mappedPath,
    exports: publicExports(text, extension),
    imports: directImports(text, extension),
    test: allPaths.has(testPath) ? testPath : null,
    ...measure(buffer),
  };
}));
const outputLines = [
  "# Module map",
  "",
  "Generated by `node tools/module_map.mjs`. Do not edit.",
  "",
  "Directories are relative to `src/`. L/B/M is lines/bytes/longest line.",
  "T+ means the adjacent `.test.mjs` exists; T- means missing. E is exports; I is imports",
  "(`.mjs` import suffixes omitted; `@/` abbreviates `../../`).",
  "",
];
let currentDirectory;
const rowGroup = row => `${dirname(row.path)}/${row.path}`;
const groupedRows = rows.sort((left, right) => compareText(rowGroup(left), rowGroup(right)));
for (const row of groupedRows) {
  const sourcePath = row.path.startsWith("src/") ? row.path.slice(4) : row.path;
  const directory = dirname(sourcePath);
  if (directory !== currentDirectory) {
    outputLines.push(`## ${directory === "." ? "." : `${directory}/`}`, "");
    currentDirectory = directory;
  }
  const fileName = sourcePath.split("/").at(-1);
  outputLines.push(
    ...compactModuleFields(
      `- ${fileName} ${row.lines}/${row.bytes}/${row.longestLineBytes} T${row.test ? "+" : "-"}`,
      [...fieldLines("E", row.exports), ...fieldLines("I", row.imports)],
    ),
  );
}
outputLines.push("");
const output = outputLines.join("\n");

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, output, "utf8");
console.log(`Wrote docs/module-map.md (${rows.length} modules).`);
