#!/usr/bin/env node
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, extname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { compactModuleFields } from "./module_map_format.mjs";
const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = resolve(repositoryRoot, "src");
const outputPath = resolve(repositoryRoot, "docs/module-map.md");
const SOURCE_EXTENSIONS = new Set([".cjs", ".css", ".html", ".js", ".mjs"]);
const TEST_SUFFIX = ".test.mjs";

function compareText(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function repositoryPath(path) {
  return relative(repositoryRoot, path).split(sep).join("/");
}

async function collectSourceFiles(directory, files = []) {
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      await collectSourceFiles(path, files);
    } else if (entry.isFile() && SOURCE_EXTENSIONS.has(extname(entry.name).toLowerCase())) {
      files.push(path);
    }
  }
  return files;
}

function uniqueSorted(values) {
  return [...new Set(values)].sort(compareText);
}

function publicExports(text, extension) {
  if (![".cjs", ".js", ".mjs"].includes(extension)) return [];
  const names = [];
  const declaration = /\bexport\s+(?:async\s+)?(?:class|const|function|let|var)\s+([A-Za-z_$][\w$]*)/g;
  const named = /\bexport\s*\{([^}]*)\}/g;
  const namespace = /\bexport\s*\*\s+as\s+([A-Za-z_$][\w$]*)\s+from\b/g;
  let match;
  if (/\bexport\s+default\b/.test(text)) names.push("default");
  while ((match = declaration.exec(text))) names.push(match[1]);
  while ((match = namespace.exec(text))) names.push(match[1]);
  while ((match = named.exec(text))) {
    for (const item of match[1].split(",")) {
      const parts = item.trim().split(/\s+as\s+/);
      if (parts[0]) names.push(parts.at(-1).trim());
    }
  }
  if (/\bexport\s*\*\s+from\b/.test(text)) names.push("*");
  return uniqueSorted(names);
}

function directImports(text, extension) {
  const imports = [];
  const staticImport = /\bimport\s+(?:[^"'`;]*?\s+from\s+)?["']([^"']+)["']/g;
  const dynamicImport = /\bimport\s*\(\s*["']([^"']+)["']/g;
  const reExport = /\bexport\s+(?:\*(?:\s+as\s+\w+)?|\{[^}]*\})\s+from\s+["']([^"']+)["']/g;
  const htmlDependency = /<(?:link|script)\b[^>]*?\b(?:href|src)\s*=\s*["']([^"']+)["']/gi;
  const cssImport = /@import\s+(?:url\(\s*)?["']?([^"')\s;]+)/gi;
  const patterns = [staticImport, dynamicImport, reExport];
  if (extension === ".html") patterns.push(htmlDependency);
  if (extension === ".css") patterns.push(cssImport);
  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(text))) imports.push(match[1]);
  }
  return uniqueSorted(imports);
}

function measure(buffer) {
  const lines = buffer.toString("utf8").split(/\r?\n/);
  if (lines.at(-1) === "") lines.pop();
  return {
    lines: lines.length,
    bytes: buffer.length,
    longestLineBytes: lines.reduce(
      (longest, line) => Math.max(longest, Buffer.byteLength(line)),
      0,
    ),
  };
}

function code(value) {
  return `\`${value.replaceAll("|", "\\|")}\``;
}

function fieldLines(label, values) {
  if (!values.length) return [];
  const lines = [];
  let line = `  - ${label} `;
  const tokens = values.map((value, index) => (
    `${value}${index === values.length - 1 ? "" : ", "}`
  ));
  for (const token of tokens) {
    if (Buffer.byteLength(line + token) > 150) {
      lines.push(line);
      line = `    ${token}`;
    } else {
      line += token;
    }
  }
  lines.push(line);
  return lines;
}

const sourceFiles = (await collectSourceFiles(sourceRoot)).sort(compareText);
const allPaths = new Set(sourceFiles.map(repositoryPath));
const modules = sourceFiles.filter(path => !path.endsWith(TEST_SUFFIX));
const rows = await Promise.all(modules.map(async path => {
  const buffer = await readFile(path);
  const text = buffer.toString("utf8");
  const extension = extname(path).toLowerCase();
  const mappedPath = repositoryPath(path);
  const testPath = mappedPath.replace(/\.[^.]+$/, TEST_SUFFIX);
  return {
    path: mappedPath,
    exports: publicExports(text, extension),
    imports: directImports(text, extension),
    test: allPaths.has(testPath) ? testPath : null,
    ...measure(buffer),
  };
}));

const outputLines = [
  "# Module map",
  "",
  "Generated by `node tools/module_map.mjs`. Do not edit.",
  "",
  "Rows show L/B/M (lines/bytes/longest line), T (test beside module), E (exports), and I (imports).",
  "",
];
for (const row of rows) {
  const test = row.test ? code(basename(row.test)) : "**MISSING**";
  outputLines.push(
    ...compactModuleFields(
      `- ${code(row.path)} — ${row.lines}/${row.bytes}/${row.longestLineBytes}; T ${test}`,
      [...fieldLines("E", row.exports), ...fieldLines("I", row.imports)],
    ),
  );
}
outputLines.push("");
const output = outputLines.join("\n");

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, output, "utf8");
console.log(`Wrote docs/module-map.md (${rows.length} modules).`);
