// FEATURE:      Sharded module-map documents
// SURFACE:      moduleMapDocuments(rows), isModuleMapDocumentName(name)
// WHY TOGETHER: Shard partitioning, filenames, and the index are one generated-document contract
// STATE:        None
// RULES:        Every document remains below the authored-file context targets
// PROVENANCE:   Scope/coding_pattern.md generated module-map requirement

import { formatModuleShard } from "./module_map_format.mjs";

const TARGET_LINES = 140;
const TARGET_BYTES = 9_000;
const documentNamePattern = /^module-map(?:-[a-z0-9-]+)?\.md$/;

function compareText(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function rowSortKey(row) {
  const separator = row.path.lastIndexOf("/");
  return `${row.path.slice(0, separator)}/${row.path}`;
}

function moduleLayer(path) {
  const sourcePath = path.startsWith("src/") ? path.slice(4) : path;
  const separator = sourcePath.indexOf("/");
  return separator === -1 ? "." : sourcePath.slice(0, separator);
}

function shardSlug(layer) {
  if (layer === ".") return "root";
  const slug = layer.toLowerCase().replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  if (!slug) throw new TypeError(`Cannot derive module-map shard name from ${layer}`);
  return slug;
}

function fitsTarget(content) {
  const lines = content.endsWith("\n")
    ? content.slice(0, -1).split("\n").length
    : content.split("\n").length;
  return lines <= TARGET_LINES && Buffer.byteLength(content) <= TARGET_BYTES;
}

function partitionLayer(layer, rows) {
  const partitions = [];
  let current = [];
  for (const row of rows) {
    const candidate = [...current, row];
    if (fitsTarget(formatModuleShard(layer, candidate))) {
      current = candidate;
      continue;
    }
    if (!current.length) {
      throw new RangeError(`${row.path} cannot fit in one module-map shard`);
    }
    partitions.push(current);
    current = [row];
    if (!fitsTarget(formatModuleShard(layer, current))) {
      throw new RangeError(`${row.path} cannot fit in one module-map shard`);
    }
  }
  if (current.length) partitions.push(current);
  return partitions;
}

function shardName(layer, index, count) {
  const suffix = count === 1 ? "" : `-${String(index + 1).padStart(2, "0")}`;
  return `module-map-${shardSlug(layer)}${suffix}.md`;
}

function indexDocument(shards, moduleCount) {
  const lines = [
    "# Module map",
    `Generated by \`node tools/module_map.mjs\`; ${moduleCount} modules.`,
    "Open the source-layer shards for paths, exports, imports, tests, lines, and bytes.",
    "",
  ];
  for (const shard of shards) {
    const part = shard.partCount === 1
      ? ""
      : ` (${shard.partIndex + 1}/${shard.partCount})`;
    const label = shard.layer === "." ? "src/" : `src/${shard.layer}/`;
    lines.push(
      `- [${label}${part}](${shard.name}) — ${shard.rows.length} modules`,
    );
  }
  lines.push("");
  const content = lines.join("\n");
  if (!fitsTarget(content)) {
    throw new RangeError("Module-map index exceeds its context target");
  }
  return { name: "module-map.md", content };
}

export function isModuleMapDocumentName(name) {
  return documentNamePattern.test(name);
}

export function moduleMapDocuments(rows) {
  const sorted = [...rows].sort((left, right) => (
    compareText(rowSortKey(left), rowSortKey(right))
  ));
  const layers = new Map();
  for (const row of sorted) {
    const layer = moduleLayer(row.path);
    const group = layers.get(layer) ?? [];
    group.push(row);
    layers.set(layer, group);
  }
  const shards = [];
  const slugs = new Set();
  for (const [layer, layerRows] of [...layers].sort(([left], [right]) => (
    compareText(left, right)
  ))) {
    const slug = shardSlug(layer);
    if (slugs.has(slug)) throw new TypeError(`Duplicate module-map shard slug: ${slug}`);
    slugs.add(slug);
    const partitions = partitionLayer(layer, layerRows);
    partitions.forEach((partition, partIndex) => {
      shards.push({
        layer,
        rows: partition,
        partIndex,
        partCount: partitions.length,
        name: shardName(layer, partIndex, partitions.length),
        content: formatModuleShard(layer, partition),
      });
    });
  }
  return [
    indexDocument(shards, sorted.length),
    ...shards.map(({ name, content }) => ({ name, content })),
  ];
}
